name: DeadlierNights
main: someguy.deadliernights.DeadlierNights
version: 0.03a
author: Someguyfromcrowd

commands:
  DNchat:
    description: Enables or disables chat messages for DeadlierNights
    usage: /dnchat [true/false]
    permission: DeadlierNights.set.chat
    permission-message: You don't have permission to use that command!
  DNlog:
    description: Enables or disables log messages for DeadlierNights
    usage: /dnlog [true/false]
    permission: DeadlierNights.set.log
    permission-message: You don't have permission to use that command!
  DNdecay:
    description: Sets the decay rate for DeadlierNights
    usage: /dndecay [positive integer/zero]
    permission: DeadlierNights.set.decay
    permission-message: You don't have permission to use that command!
  DNpotion:
    description: Enables or disables potion debuffs
    usage: /dnpotion [true/false]
    permission: DeadlierNights.set.potion
    permission-message: You don't have permission to use that command!
  DNmob:
    description: Enables or disables mob buffs
    usage: /dnmob [true/false]
    permission: DeadlierNights.set.mob
    permission-message: You don't have permission to use that command!
  DNreload:
    description: Reloads settings for DeadlierNights
    usage: /dnreload
    permission: DeadlierNights.reload
    permission-message: You don't have permission to use that command!
  DNexempt:
    description: Gives the player immunity to DeadlierNights' effects
    usage: /dnexempt [true/false]
    permission: DeadlierNights.exempt
    permission-message: You don't have permission to use that command!
  DNexempto:
    description: Gives another player immunity to DeadlierNights' effects
    usage: /dnexempto [name] [true/false]
    permission: DeadlierNights.exempt.others
    permission-message: You don't have permission to use that command!

permissions:
   deadliernights.*:
     description: Gives access to all commands
     children:
       deadliernights.set.chat: true
       deadliernights.set.log: true
       deadliernights.set.decay: true
       deadliernights.set.potion: true
       deadliernights.set.mob: true
       deadliernights.reload: true
       deadliernights.exempt: true
       deadliernights.exempt.others: true
     default: op
   deadliernights.set.*:
     description: Gives access to all set commands
     children:
       deadliernights.set.chat: true
       deadliernights.set.log: true
       deadliernights.set.decay: true
       deadliernights.set.potion: true
       deadliernights.set.mob: true
   deadliernights.set.chat:
     description: Allows toggling of chat messages for players
   deadliernights.set.log:
     description: Allows toggling of log messages
   deadliernights.set.decay:
     description: Allows for the exposure decay rate to be set
   deadliernights.set.potion:
     description: Allows for the toggling of potion debuffs
   deadliernights.set.mob:
     description: Allows for the toggling of mob buffs
   deadliernights.reload:
     description: Allows for reloading of DeadlierNights' configuration files
   deadliernights.exempt:
     description: Allows the player to make him/her self immune to DeadlierNights' debuffs
   deadliernights.exempt.others:
     description: As with exempt, but also allows for other players to be affected